CREATE TABLE IF NOT EXISTS gold_fiscal_monetary (
    country_code            VARCHAR(3)      NOT NULL,
    country                 TEXT            NOT NULL,
    year                    INTEGER         NOT NULL,
    govdebt_gdp             DOUBLE PRECISION,
    debt_change_yoy         DOUBLE PRECISION,
    govrev_gdp              DOUBLE PRECISION,
    govexp_gdp              DOUBLE PRECISION,
    fiscal_balance_gdp      DOUBLE PRECISION,
    cumulative_deficit_5yr  DOUBLE PRECISION,
    ltrate                  DOUBLE PRECISION,
    infl                    DOUBLE PRECISION,
    real_interest_rate      DOUBLE PRECISION,
    tax_revenue_pct_gdp     DOUBLE PRECISION,
    inflation_cpi           DOUBLE PRECISION,
    inflation_deflator      DOUBLE PRECISION,
    inflation_gap           DOUBLE PRECISION,
    rolling_3yr_avg_cpi     DOUBLE PRECISION,
    income_group            TEXT,
    development_group       TEXT,
    completeness_score      DOUBLE PRECISION,
    PRIMARY KEY (country_code, year)
);
