ITEM_CODE_MAP = {
    "22008": "gdp_value",
    "22015": "gfcf_value",
    "22011": "gni_value",
    "22016": "agri_va",
    "22075": "manuf_va",
    "22076": "va_foodbev",
}

COUNTRY_ISO3_MAP = {
    "Canada":                                              "CAN",
    "United States of America":                            "USA",
    "Mexico":                                              "MEX",
    "Guatemala":                                           "GTM",
    "Belize":                                              "BLZ",
    "El Salvador":                                         "SLV",
    "Honduras":                                            "HND",
    "Nicaragua":                                           "NIC",
    "Costa Rica":                                          "CRI",
    "Panama":                                              "PAN",
    "Cuba":                                                "CUB",
    "Jamaica":                                             "JAM",
    "Haiti":                                               "HTI",
    "Dominican Republic":                                  "DOM",
    "Colombia":                                            "COL",
    "Venezuela (Bolivarian Republic of)":                  "VEN",
    "Guyana":                                              "GUY",
    "Suriname":                                            "SUR",
    "Ecuador":                                             "ECU",
    "Peru":                                                "PER",
    "Brazil":                                              "BRA",
    "Bolivia (Plurinational State of)":                    "BOL",
    "Paraguay":                                            "PRY",
    "Chile":                                               "CHL",
    "Argentina":                                           "ARG",
    "Uruguay":                                             "URY",
    "Russian Federation":                                  "RUS",
    "Norway":                                              "NOR",
    "Sweden":                                              "SWE",
    "Finland":                                             "FIN",
    "Iceland":                                             "ISL",
    "United Kingdom of Great Britain and Northern Ireland": "GBR",
    "Ireland":                                             "IRL",
    "France":                                              "FRA",
    "Spain":                                               "ESP",
    "Portugal":                                            "PRT",
    "Germany":                                             "DEU",
    "Poland":                                              "POL",
    "Ukraine":                                             "UKR",
    "Belarus":                                             "BLR",
    "Romania":                                             "ROU",
    "Italy":                                               "ITA",
    "Greece":                                              "GRC",
    "Türkiye":                                             "TUR",
    "Kazakhstan":                                          "KAZ",
    "Mongolia":                                            "MNG",
    "China; mainland":                                     "CHN",
    "Japan":                                               "JPN",
    "Republic of Korea":                                   "KOR",
    "India":                                               "IND",
    "Pakistan":                                            "PAK",
    "Afghanistan":                                         "AFG",
    "Iran (Islamic Republic of)":                          "IRN",
    "Saudi Arabia":                                        "SAU",
    "Yemen":                                               "YEM",
    "Oman":                                                "OMN",
    "Thailand":                                            "THA",
    "Viet Nam":                                            "VNM",
    "Lao People's Democratic Republic":                    "LAO",
    "Cambodia":                                            "KHM",
    "Myanmar":                                             "MMR",
    "Malaysia":                                            "MYS",
    "Indonesia":                                           "IDN",
    "Philippines":                                         "PHL",
    "Australia":                                           "AUS",
    "New Zealand":                                         "NZL",
    "Papua New Guinea":                                    "PNG",
    "South Africa":                                        "ZAF",
    "Namibia":                                             "NAM",
    "Botswana":                                            "BWA",
    "Zimbabwe":                                            "ZWE",
    "Mozambique":                                          "MOZ",
    "Angola":                                              "AGO",
    "Zambia":                                              "ZMB",
    "United Republic of Tanzania":                         "TZA",
    "Kenya":                                               "KEN",
    "Ethiopia":                                            "ETH",
    "Sudan":                                               "SDN",
    "Egypt":                                               "EGY",
    "Libya":                                               "LBY",
    "Algeria":                                             "DZA",
    "Morocco":                                             "MAR",
    "Mali":                                                "MLI",
    "Mauritania":                                          "MRT",
    "Niger":                                               "NER",
    "Chad":                                                "TCD",
    "Nigeria":                                             "NGA",
    "Madagascar":                                          "MDG",
}
